// Package memory реализует долгосрочную и рабочую память проекта.
package memory

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

const (
	// LongTermSummaryThreshold — максимальное количество записей в долгосрочной памяти
	// до автоматического summary самых старых записей.
	LongTermSummaryThreshold = 20
)

// Entry — одна запись памяти проекта.
type Entry struct {
	ID              string    `json:"id"`
	Type            string    `json:"type"`
	Title           string    `json:"title"`
	Content         string    `json:"content"`
	Tags            []string  `json:"tags,omitempty"`
	SourceSessionID string    `json:"source_session_id,omitempty"`
	AutoGenerated   bool      `json:"auto_generated,omitempty"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// Memory — состояние памяти проекта.
type Memory struct {
	LongTerm []Entry `json:"long_term"`
	Working  []Entry `json:"working"`
}

// Store описывает хранилище памяти проекта.
type Store interface {
	Load(projectID string) (Memory, error)
	Save(projectID string, mem Memory) error
}

// FileStore сохраняет память каждого проекта в отдельном JSON-файле.
type FileStore struct {
	baseDir string
	mu      sync.Mutex
	locks   map[string]*sync.Mutex
}

// NewFileStore создаёт файловое хранилище памяти в указанном каталоге.
func NewFileStore(baseDir string) (*FileStore, error) {
	if err := os.MkdirAll(baseDir, 0o755); err != nil {
		return nil, fmt.Errorf("не удалось создать каталог памяти %q: %w", baseDir, err)
	}

	return &FileStore{
		baseDir: baseDir,
		locks:   make(map[string]*sync.Mutex),
	}, nil
}

// Load возвращает сохранённую память проекта.
func (s *FileStore) Load(projectID string) (Memory, error) {
	if err := ValidateProjectID(projectID); err != nil {
		return Memory{}, err
	}

	path := s.projectFile(projectID)

	s.lock(projectID).Lock()
	defer s.unlock(projectID)

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return Memory{LongTerm: []Entry{}, Working: []Entry{}}, nil
		}
		return Memory{}, fmt.Errorf("не удалось прочитать память проекта %q: %w", projectID, err)
	}

	var mem Memory
	if err := json.Unmarshal(data, &mem); err != nil {
		return Memory{}, fmt.Errorf("не удалось распарсить память проекта %q: %w", projectID, err)
	}

	if mem.LongTerm == nil {
		mem.LongTerm = []Entry{}
	}
	if mem.Working == nil {
		mem.Working = []Entry{}
	}

	return mem, nil
}

// Save атомарно сохраняет память проекта.
func (s *FileStore) Save(projectID string, mem Memory) error {
	if err := ValidateProjectID(projectID); err != nil {
		return err
	}

	now := time.Now().UTC()
	for i := range mem.LongTerm {
		if mem.LongTerm[i].CreatedAt.IsZero() {
			mem.LongTerm[i].CreatedAt = now
		}
		mem.LongTerm[i].UpdatedAt = now
	}
	for i := range mem.Working {
		if mem.Working[i].CreatedAt.IsZero() {
			mem.Working[i].CreatedAt = now
		}
		mem.Working[i].UpdatedAt = now
	}

	data, err := json.MarshalIndent(mem, "", "  ")
	if err != nil {
		return fmt.Errorf("не удалось сериализовать память проекта %q: %w", projectID, err)
	}

	path := s.projectFile(projectID)

	s.lock(projectID).Lock()
	defer s.unlock(projectID)

	tmp, err := os.CreateTemp(s.baseDir, ".memory-*.tmp")
	if err != nil {
		return fmt.Errorf("не удалось создать временный файл для памяти %q: %w", projectID, err)
	}

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return fmt.Errorf("не удалось записать память проекта %q: %w", projectID, err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmp.Name())
		return fmt.Errorf("не удалось закрыть временный файл памяти %q: %w", projectID, err)
	}

	if err := os.Rename(tmp.Name(), path); err != nil {
		os.Remove(tmp.Name())
		return fmt.Errorf("не удалось сохранить память проекта %q: %w", projectID, err)
	}

	return nil
}

// UpsertEntry добавляет новую запись или обновляет существующую по id.
// Если entry.ID пустой, генерируется новый уникальный идентификатор.
// При смене типа запись перемещается между уровнями памяти.
func UpsertEntry(mem *Memory, entry Entry) error {
	if mem.LongTerm == nil {
		mem.LongTerm = []Entry{}
	}
	if mem.Working == nil {
		mem.Working = []Entry{}
	}

	if entry.Type == "" {
		return fmt.Errorf("тип записи не может быть пустым")
	}
	if entry.Title == "" {
		return fmt.Errorf("заголовок записи не может быть пустым")
	}
	if !isLongTerm(entry.Type) && !isWorking(entry.Type) {
		return fmt.Errorf("неизвестный тип записи: %s", entry.Type)
	}

	now := time.Now().UTC()
	if entry.ID == "" {
		entry.ID = generateID()
		entry.CreatedAt = now
	}
	entry.UpdatedAt = now

	// Удаляем существующую запись с таким id из любого уровня.
	_ = DeleteEntry(mem, entry.ID)

	if isLongTerm(entry.Type) {
		mem.LongTerm = append(mem.LongTerm, entry)
	} else {
		mem.Working = append(mem.Working, entry)
	}
	return nil
}

// DeleteEntry удаляет запись по id из любого уровня памяти.
func DeleteEntry(mem *Memory, entryID string) error {
	if entryID == "" {
		return fmt.Errorf("id записи не может быть пустым")
	}

	for level, entries := range [][]Entry{mem.LongTerm, mem.Working} {
		for i, e := range entries {
			if e.ID == entryID {
				if level == 0 {
					mem.LongTerm = append(entries[:i], entries[i+1:]...)
				} else {
					mem.Working = append(entries[:i], entries[i+1:]...)
				}
				return nil
			}
		}
	}

	return fmt.Errorf("запись %q не найдена", entryID)
}

// OldestLongTerm возвращает самые старые записи long_term, которые выходят за порог.
// Оставшиеся записи сохраняют исходный порядок.
func OldestLongTerm(mem Memory) (oldest []Entry, remaining []Entry) {
	if len(mem.LongTerm) <= LongTermSummaryThreshold {
		return nil, mem.LongTerm
	}

	count := len(mem.LongTerm) - LongTermSummaryThreshold

	// Сортируем копию по CreatedAt для определения самых старых записей.
	sorted := make([]Entry, len(mem.LongTerm))
	copy(sorted, mem.LongTerm)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sorted[i].CreatedAt.Before(sorted[j].CreatedAt)
	})

	oldest = sorted[:count]

	// Собираем оставшиеся записи в исходном порядке.
	idsToRemove := make(map[string]struct{}, count)
	for _, e := range oldest {
		idsToRemove[e.ID] = struct{}{}
	}
	for _, e := range mem.LongTerm {
		if _, ok := idsToRemove[e.ID]; !ok {
			remaining = append(remaining, e)
		}
	}

	return oldest, remaining
}

// ValidateProjectID проверяет, что идентификатор проекта безопасен.
func ValidateProjectID(projectID string) error {
	if strings.TrimSpace(projectID) == "" {
		return fmt.Errorf("project_id не может быть пустым")
	}
	if strings.Contains(projectID, "..") {
		return fmt.Errorf("project_id не может содержать '..'")
	}
	// Разрешены буквы, цифры, пробелы, дефисы, подчёркивания.
	valid := regexp.MustCompile(`^[\p{L}\p{N}\s\-_]+$`)
	if !valid.MatchString(projectID) {
		return fmt.Errorf("project_id содержит недопустимые символы")
	}
	return nil
}

// projectFile возвращает безопасный путь к файлу памяти проекта.
func (s *FileStore) projectFile(projectID string) string {
	filename := sanitizeProjectID(projectID) + ".json"
	return filepath.Join(s.baseDir, filename)
}

// sanitizeProjectID превращает project_id в безопасное имя файла.
func sanitizeProjectID(projectID string) string {
	s := strings.TrimSpace(projectID)
	s = strings.ReplaceAll(s, " ", "_")
	s = url.PathEscape(s)
	return s
}

// lock возвращает мьютекс для указанного проекта, создавая его при необходимости.
func (s *FileStore) lock(projectID string) *sync.Mutex {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.locks[projectID] == nil {
		s.locks[projectID] = &sync.Mutex{}
	}
	return s.locks[projectID]
}

// unlock освобождает мьютекс проекта.
func (s *FileStore) unlock(projectID string) {
	s.lock(projectID).Unlock()
}

// isLongTerm возвращает true, если тип записи относится к долгосрочной памяти.
func isLongTerm(entryType string) bool {
	switch entryType {
	case "technology", "pattern", "principle", "knowledge", "summary", InvariantsEntryType:
		return true
	}
	return false
}

// isWorking возвращает true, если тип записи относится к рабочей памяти.
func isWorking(entryType string) bool {
	switch entryType {
	case "task", "entity":
		return true
	}
	return false
}

// generateID генерирует короткий уникальный идентификатор.
func generateID() string {
	return fmt.Sprintf("mem_%d", time.Now().UnixNano())
}
