package agent

import (
	"encoding/json"
	"strings"
	"testing"
	"time"

	"ai-chat/internal/memory"
	"ai-chat/internal/profile"
)

type mockAPIClient struct {
	response string
	err      error
}

func (m *mockAPIClient) Call(payload []byte) ([]byte, error) {
	if m.err != nil {
		return nil, m.err
	}

	return json.Marshal(map[string]interface{}{
		"choices": []map[string]interface{}{
			{
				"message": map[string]string{
					"content": m.response,
				},
				"finish_reason": "stop",
			},
		},
		"usage": map[string]int{
			"prompt_tokens":     10,
			"completion_tokens": 5,
			"total_tokens":      15,
		},
	})
}

func TestFormatProjectContext(t *testing.T) {
	mem := memory.Memory{
		LongTerm: []memory.Entry{
			{Type: "principle", Title: "SOLID", Content: "Принципы ООП"},
			{Type: "technology", Title: "Go", Content: "Язык программирования"},
			{Type: "pattern", Title: "Repository"},
			{Type: "knowledge", Title: "Факт"},
		},
		Working: []memory.Entry{
			{Type: "task", Title: "Сделать авторизацию", Content: "JWT"},
			{Type: "entity", Title: "User"},
		},
	}

	ctx := formatProjectContext(mem)
	if ctx == "" {
		t.Fatal("expected non-empty context")
	}

	expectedParts := []string{
		"Контекст проекта:",
		"Принципы:",
		"SOLID: Принципы ООП",
		"Технологии:",
		"Go: Язык программирования",
		"Паттерны:",
		"Repository",
		"Знания:",
		"Факт",
		"Текущие задачи:",
		"Сделать авторизацию: JWT",
		"Сущности:",
		"User",
	}
	for _, part := range expectedParts {
		if !strings.Contains(ctx, part) {
			t.Errorf("expected context to contain %q, got:\n%s", part, ctx)
		}
	}
}

func TestFormatProjectContextEmpty(t *testing.T) {
	ctx := formatProjectContext(memory.Memory{})
	if ctx != "" {
		t.Fatalf("expected empty context, got %q", ctx)
	}
}

func TestSummarizeLongTermMemoryIfNeeded(t *testing.T) {
	now := time.Now().UTC()
	mem := memory.Memory{}
	for i := 0; i < 22; i++ {
		mem.LongTerm = append(mem.LongTerm, memory.Entry{
			ID:        string(rune('a' + i)),
			Type:      "knowledge",
			Title:     "Fact",
			Content:   "Content",
			CreatedAt: now.Add(time.Duration(i) * time.Hour),
		})
	}

	tmp := t.TempDir()
	store, err := memory.NewFileStore(tmp)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	client := &mockAPIClient{response: "Обобщённые знания проекта"}
	cfg := Config{APIFormat: "openai", Model: "test", SummaryMaxTokens: 500}
	agent := NewSimpleAgent(cfg, client).WithMemory(store)

	result, err := agent.summarizeLongTermMemoryIfNeeded("proj", mem)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(result.LongTerm) != 21 {
		t.Fatalf("expected 21 long_term entries after summary, got %d", len(result.LongTerm))
	}

	hasSummary := false
	for _, e := range result.LongTerm {
		if e.Type == "summary" {
			hasSummary = true
			if !e.AutoGenerated {
				t.Fatal("expected summary to be auto_generated")
			}
			if e.Content != "Обобщённые знания проекта" {
				t.Fatalf("unexpected summary content: %q", e.Content)
			}
		}
	}
	if !hasSummary {
		t.Fatal("expected summary entry")
	}

	// Повторный вызов не должен генерировать ещё один summary.
	result2, err := agent.summarizeLongTermMemoryIfNeeded("proj", result)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	summaryCount := 0
	for _, e := range result2.LongTerm {
		if e.Type == "summary" {
			summaryCount++
		}
	}
	if summaryCount != 1 {
		t.Fatalf("expected 1 summary entry, got %d", summaryCount)
	}
}

func TestFormatUserProfileContext(t *testing.T) {
	p := profile.Profile{Name: "Разработчик", Description: "Люблю Go и чистую архитектуру."}
	ctx := formatUserProfileContext(p)
	if !strings.Contains(ctx, "Профиль пользователя:") {
		t.Fatalf("expected profile header, got %q", ctx)
	}
	if !strings.Contains(ctx, "Люблю Go") {
		t.Fatalf("expected description content, got %q", ctx)
	}

	empty := formatUserProfileContext(profile.Profile{Name: "Empty"})
	if empty != "" {
		t.Fatalf("expected empty context for empty description, got %q", empty)
	}
}

func TestSummarizeMemoryIfNeededNoThreshold(t *testing.T) {
	tmp := t.TempDir()
	store, _ := memory.NewFileStore(tmp)
	client := &mockAPIClient{response: "test"}
	cfg := Config{APIFormat: "openai", Model: "test"}
	agent := NewSimpleAgent(cfg, client).WithMemory(store)

	mem := memory.Memory{
		LongTerm: []memory.Entry{
			{ID: "1", Type: "principle", Title: "SOLID"},
		},
	}
	if err := store.Save("proj", mem); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	result, err := agent.SummarizeMemoryIfNeeded("proj")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result.LongTerm) != 1 {
		t.Fatalf("expected 1 entry, got %d", len(result.LongTerm))
	}
}

func TestSummarizeLongTermMemoryPreservesInvariants(t *testing.T) {
	now := time.Now().UTC()
	mem := memory.Memory{}
	for i := 0; i < 22; i++ {
		mem.LongTerm = append(mem.LongTerm, memory.Entry{
			ID:        string(rune('a' + i)),
			Type:      "knowledge",
			Title:     "Fact",
			Content:   "Content",
			CreatedAt: now.Add(time.Duration(i) * time.Hour),
		})
	}
	// Добавляем инварианты как самую старую запись.
	mem.LongTerm = append([]memory.Entry{{
		ID:        "inv",
		Type:      memory.InvariantsEntryType,
		Title:     "Инварианты проекта",
		Content:   "invariants:\n  - title: X\n    category: stack\n    severity: hard\n    active: true\n",
		CreatedAt: now.Add(-time.Hour),
	}}, mem.LongTerm...)

	tmp := t.TempDir()
	store, err := memory.NewFileStore(tmp)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	client := &mockAPIClient{response: "Обобщённые знания проекта"}
	cfg := Config{APIFormat: "openai", Model: "test", SummaryMaxTokens: 500}
	agent := NewSimpleAgent(cfg, client).WithMemory(store)

	result, err := agent.summarizeLongTermMemoryIfNeeded("proj", mem)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Инварианты должны остаться, при этом появиться summary.
	hasInvariants := false
	hasSummary := false
	for _, e := range result.LongTerm {
		if e.Type == memory.InvariantsEntryType {
			hasInvariants = true
		}
		if e.Type == "summary" {
			hasSummary = true
		}
	}
	if !hasInvariants {
		t.Fatal("expected invariants entry to be preserved")
	}
	if !hasSummary {
		t.Fatal("expected summary entry")
	}
}
